<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lidar_accelerator</name>
  <version>0.0.0</version>
  <description>pybind11 기반 Go2 LiDAR CPU 가속 모듈</description>

  <maintainer email="todo@example.com">todo</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>pybind11_vendor</build_depend>
  <build_depend>pybind11</build_depend>

  <depend>ament_index_cpp</depend>

  <exec_depend>python3-numpy</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
