/teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 3
    scale_linear:
      x: 0.2
      y: 0.2

    axis_angular:
      yaw: 6
    scale_angular:
      yaw: 0.2

    require_enable_button: false


/twist_mux:
  ros__parameters:
    topics:
      joy:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 10
